
POST  http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:getAddressById>
            <arg0>1</arg0>
        </jets:getAddressById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:getAll>

        </jets:getAll>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:getCustomerByAddress>
 <arg0>5</arg0>
        </jets:getCustomerByAddress>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:getStaffByAddress>
 <arg0>3</arg0>
        </jets:getStaffByAddress>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:getStoreByAddress>
 <arg0>1</arg0>
        </jets:getStoreByAddress>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:addAddress>
              <arg0>
                 <address>47 salah salem </address>
        <district>Alberta</district>
        
       
        <phone></phone>
        <postalCode></postalCode>
      <city><id>576</id></city>

            </arg0>
        </jets:addAddress>
        </jets:add>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakilaApi/ws/address HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.soap.api.example.org/"
    xmlns:tns="http://webServices.soap.api.example.org/"
>
    <soap:Body>
        <jets:updateAddress>
            <arg0>
                 <address>47 MySakila Drive</address>
        <district>Alberta</district>
        <id>1</id>
      
        <phone></phone>
        <postalCode></postalCode>
      <city><id>576</id></city>

            </arg0>
        </jets:updateAddress>
    </soap:Body>
</soap:Envelope>

