POST  http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getCustomerById>
            <arg0>1</arg0>
        </jets:getCustomerById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getAll>

        </jets:getAll>
    </soap:Body>
</soap:Envelope>
###
POST http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:add>
            <arg0>

                <active>true</active>
                <address>

                    <id>5</id>

                </address>

                <email>omniaAyman@sakilacustomer.org</email>
                <firstName>Alaa Ayman</firstName>

                <lastName>Ayman</lastName>

                <store>


                    <id>2</id>
                </store>

            </arg0>
        </jets:add>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:update>
            <arg0>
                <id>1</id>
                <active>true</active>
                <address>

                    <id>5</id>

                </address>

                <email>omniaAyman@sakilacustomer.org</email>
                <firstName>Alaa Ayman</firstName>

                <lastName>Ayman</lastName>

                <store>


                    <id>2</id>
                </store>

            </arg0>
        </jets:update>
    </soap:Body>
</soap:Envelope>

###


POST  http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getHomeStore>
            <arg0>1</arg0>
        </jets:getHomeStore>
    </soap:Body>
</soap:Envelope>

###


POST  http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getCustomerAddress>
            <arg0>1</arg0>
        </jets:getCustomerAddress>
    </soap:Body>
</soap:Envelope>

###


POST  http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getCustomerRents>
            <arg0>1</arg0>
        </jets:getCustomerRents>
    </soap:Body>
</soap:Envelope>
###


POST  http://localhost:8090/sakilaApi/ws/customer HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webServices.example.org/"
    xmlns:tns="http://webServices.example.org/"
>
    <soap:Body>
        <jets:getCustomerPayments>
            <arg0>1</arg0>
        </jets:getCustomerPayments>
    </soap:Body>
</soap:Envelope>
